export interface Testimonial {
  quote: string
  role: string
  company: string
  logo: string
}

export const TESTIMONIALS: Testimonial[] = [
  { quote: "Many thanks for your excellent report!", role: "Managing Director", company: "UroPharma Limited", logo: "UroPharma-25.png" },
  { quote: "Thank you! Safely received and it looks great.", role: "AI market development analyst", company: "The British Standards Institution", logo: "The British Standards Institution.png" },
  { quote: "Thanks for all the great work and quick turnaround last week. Really impressed by the work and I would happily refer you to other team members.", role: "Manager", company: "EY-Parthenon", logo: "EY-Parthenon.png" },
  { quote: "Wonderful. Thank you for your support!", role: "Director, Marketing and Communications", company: "Vector BioMed", logo: "Vector BioMed..png" },
  { quote: "I appreciate your efforts to resolve this quickly and equitably.", role: "Executive Assistant", company: "Climate by Design International", logo: "Climate by Design International.png" },
  { quote: "I have been through the PET preform report. Very insightful.", role: "Global Purchasing – Rigid Plastic", company: "LACTALIS", logo: "Rigid Plastic, LACTALIS.png" },
  { quote: "I have reviewed the revised report. This is great. It is very helpful. Thank you.", role: "Founder/CEO", company: "Paradigm Business Systems, LLC", logo: "Paradigm Business Systems, LLC.png" },
  { quote: "I have reviewed the report you sent. It seems very helpful.", role: "Clinical lab Manager", company: "AMOREPACIFIC", logo: "AMOREPACIFIC.png" },
  { quote: "I got the previous version in 2020 and I found it pretty helpful, hoping this new edition is an update or even more detailed than the last.", role: "Sr. Global Marketing Manager", company: "BD", logo: "BD.png" },
  { quote: "I've gone through the report and Excel. They look good, thanks.", role: "VP Strategy", company: "caldigit", logo: "caldigit.png" },
  { quote: "I really liked the structure of the presentation and the ease of presentation of statistical data. Very professionally prepared.", role: "Business development manager", company: "ASCANIA", logo: "ASCANIA.png" },
  { quote: "Please convey my regards to your research team. The final result seems good.", role: "Director Strategy & Business Analysis Beauty Global", company: "APTAR", logo: "APTAR.png" },
  { quote: "We have received the report India Mobile Phone Accessories Market. This is Helpful.", role: "Client Solutions Manager - Beauty Lead", company: "Amazon", logo: "Beauty Lead, Amazon.png" },
  { quote: "I am a journalist. This report has been cited by a Google VP in a short presentation.", role: "Editor in Chief", company: "Tecniche Nuove Spa", logo: "Tecniche Nuove Spa.png" },
  { quote: "I received the draft of the EIS Market report well. I think we are very close to the report, which we expected.", role: "Sales & Marketing Executive", company: "Autosilicon Inc.", logo: "Autosilicon Inc..png" },
  { quote: "Thank you for the report.", role: "Senior Industrial Engineer", company: "Delta BEC", logo: "Delta BEC.png" },
  { quote: "It looks like a very good report.", role: "VP, Market Access Strategy", company: "NAVISYNC", logo: "NAVISYNC.png" },
  { quote: "Thank you very much for your performance, support, and flexibility throughout the project—it was truly appreciated.", role: "Senior Business Development Manager", company: "GMS", logo: "GMS.png" },
  { quote: "Great stuff. Thank you.", role: "Regional Sales Manager", company: "LION Group, Inc.", logo: "LION Group, Inc..png" },
  { quote: "Thank you for the report. I appreciate the effort of your consulting team to ensure the insights provided are both current and comprehensive.", role: "Product Line Manager", company: "Tempo Communication", logo: "Tempo Communication.png" },
  { quote: "I just wanted to extend my sincere thanks to you and your team for all the hard work you all have put on this project.", role: "Lead Investigator", company: "Kessler Topaz Meltzer Check, LLP", logo: "Kessler Topaz Meltzer Check, LLP.png" },
  { quote: "We have received the requested reports. Thank you so much for your quick responses, continuous support and on time delivery of reports.", role: "Working student research and project management", company: "Amrop Partnership SC", logo: "amrop_logo_rgb.jpg" },
  { quote: "The attached report seems very interesting. Congratulations on the work!", role: "Regional Sales Manager North America", company: "BURKHARDT+WEBER", logo: "BURKHARDTWEBER.png" },
  { quote: "Thanks for the modified report. Reads good.", role: "Chief Operating Officer", company: "Typhoo India", logo: "Typhoo_India.jpg" },
  { quote: "I confirm the good receipt of the report. The report is clear and corresponds to our requirements.", role: "Purchasing Apprentice", company: "Aptar Beauty", logo: "Aptar_Beauty (1).jpg" },
  { quote: "Thank you for the report. It looks fantastic. I am looking forward to giving a very positive review of the report.", role: "Product Management Director", company: "Grow Up Group Limited", logo: "Grow Up Group Limited.jpg" },
  { quote: "I hereby confirm our complete satisfaction with the study purchased.", role: "Wood processing advisor", company: "Accueil - Ministère des Ressources naturelles", logo: "Accueil.png" },
  { quote: "I was going through the document and I have found a lot of useful information that were based on a survey result.", role: "Senior Consultant", company: "PWC", logo: "PwC-logo.jpg" },
  { quote: "We received the report, and everything is fine. Thank you very much for your patience and prompt communication.", role: "Marketing and UX Research Department", company: "Mobile TeleSystems", logo: "Mobile_TeleSystems.png" },
  { quote: "Many thanks for your prompt response - and the positive news.", role: "Director Product Management – Commercial", company: "Koenig & Bauer Digital & Webfed", logo: "Koenig_&_Bauer_Digital_&_Webfed_AG_&_Co.KG.png" },
  { quote: "Thanks for the clarification and the comprehensive consideration. Appreciate.", role: "Sr. Marketing Manager", company: "Rich's Product", logo: "Richs_Product.png" },
  { quote: "Thanks for your note. The report was helpful.", role: "Marketing & Growth", company: "Iowa State University", logo: "Iowa_State_University.png" },
  { quote: "The market report is well-structured, and analysis appears to be extremely precise. It has exceeded my expectations.", role: "Directeur du Développement", company: "RAZEL-BEC", logo: "RAZEL-BEC.png" },
  { quote: "I think this is a fantastic start in the market research. It was definitely eye-opening.", role: "Founder, CNO", company: "Orchid Healthcare Solutions", logo: "Orchid_Healthcare_Solutions.png" },
  { quote: "We received a market study on Pyrolysis Oil Market. It has been useful to our strategy and budget teams.", role: "President and CEO", company: "EcoCarbon Innovations Inc.", logo: "ecocarbon-logo_small.png" },
  { quote: "Our CEO is very pleased with the report she received. She particularly appreciated the infographics provided.", role: "Medical Market Analyst", company: "BioOra Group", logo: "BioOra_Group.png" },
  { quote: "I wanted to extend my gratitude for providing the report on the Global Game Art Outsourcing Market.", role: "Anime Designer", company: "Winking Studios", logo: "Winking_Studios.png" },
  { quote: "The report was very detailed and professional. Great job!", role: "President + CEO", company: "Visual Communications Company, LLC", logo: "Visual_Communications_Company.png" },
  { quote: "Great! Thanks for your support!", role: "Medical Research Manager", company: "TWi Biotech", logo: "TWi_Biotech.png" },
  { quote: "I am happy with your insights. Thank you for all your great work.", role: "Business Development Director", company: "Snorkel Europe Limited", logo: "Snorkel_Europe.png" },
  { quote: "Thank you very much for your email and report. It looks like a very useful report with very good information.", role: "Head of Segments", company: "SKF Australia Pty Ltd", logo: "SKF_ Australia_Pty_Ltd.png" },
  { quote: "Thank you for this effort and explanation. This is very helpful and it makes much more sense now.", role: "Head of New Digital Services", company: "Safran Group", logo: "Safran_Group.png" },
  { quote: "We received the report on the autoinjector markets. Based on my preliminary review, we are pleased with the information.", role: "Chief Strategy Officer", company: "Rx Bandz, Inc", logo: "Rx_Bandz_Inc.png" },
  { quote: "Thank you for providing this valuable information. Your work is truly commendable.", role: "President", company: "PurePrime Solutions", logo: "PurePrime_Solutions.png" },
  { quote: "Thank you very much for your report which is so informative.", role: "General manager", company: "PHC Corporation", logo: "PHC_Corporation.png" },
  { quote: "Thank you for additional explanation.", role: "Director", company: "Analytical research, Pfizer Inc.", logo: "Pfizer.png" },
  { quote: "I appreciate your great support in Si-lens market.", role: "Manager", company: "Panasonic Industry Co., Ltd.", logo: "Panasonic_Industry.png" },
  { quote: "Thank you for providing me the report on Global Oncolytic Therapy Market. I am pleased with the final product.", role: "President", company: "Oncolys USA, Inc.", logo: "OncolysU_SA.png" },
  { quote: "I'm delighted with your reply. That's a great report.", role: "Associate, Business Strategy & Development", company: "NanoTextile Sdn Bhd", logo: "Nano_Textile_Sdn_Bhd.png" },
]
